### ISSUE TITLE
Create project on CC Labs for Beta of New Site

### ISSUE THREAD

**Issue by samanthalisae** [creativecommons/caselaw#2] opened 2018-06-15 14:44 UTC
Please create a new page on CC Labs that will be moved to the main website to be populated. @robmyers

**Comment by peterspdx** [comment] 2018-06-19 15:24
Normally, the person to whom you've assigned the issue is the one to close the issue after he's completed the task. Is this now done? If not, please reopen so Rob knows he still has to do it.

**Comment by robmyers** [comment] 2018-06-20 22:55
I've created a site at:

https://labs.creativecommons.org/caselaw/

The content files that you can edit are within the source code here - 

https://github.com/creativecommons/caselaw/tree/master/jekyll

Ignore anything that is not an .html or .md file in the "jekyll" directory. :-)

The pages that are HTML (.html) rather than Markdown (.md) are that way because they need more control over e.g. image placement than Markdown allows.

**Closed by robmyers** 2018-06-20 22:55 UTC
